In [1]:
import pandas as pd
import numpy as np

In [2]:
df_autogen = pd.read_excel('../0_data/autogenerated_clean.xlsx')
df_autogen.head()

,Long,Auto_caption,clean_text,text_sup_clean,text_deep_clean,text_deep_clean_pos,hashtags,text_deep_clean_pos_str
0,2015-11-18_18-26-59_UTC.jpg,a picture of a woman with long black hair sits...,picture long black hair sits couch front black...,a picture of a woman with long black hair sits...,picture woman long black hair sit couch front ...,"['picture NOUN', 'woman NOUN', 'long ADJ', 'bl...",[],long black hair sit couch front black firepl...
1,2015-06-01_07-45-08_UTC.jpg,a picture of a woman with black hair and a bla...,picture black hair black tattoo arm wears whit...,a picture of a woman with black hair and a bla...,picture woman black hair black tattoo arm wear...,"['picture NOUN', 'woman NOUN', 'black ADJ', 'h...",[],black hair black tattoo arm wear white dress...
2,2015-07-06_10-38-30_UTC.jpg,a picture of a woman with black hair and a bla...,picture black hair black tattoo arm poses whit...,a picture of a woman with black hair and a bla...,picture woman black hair black tattoo arm pose...,"['picture NOUN', 'woman NOUN', 'black ADJ', 'h...",[],black hair black tattoo arm pose white dress...
3,2020-04-10_08-57-20_UTC.jpg,a picture of a woman wearing a black jacket an...,picture wearing black jacket heels sits red co...,a picture of a woman wearing a black jacket an...,picture woman wear black jacket heel sit red c...,"['picture NOUN', 'woman NOUN', 'wear VERB', 'b...",[],wear black jacket heel sit red couch bare le...
4,2019-10-24_11-49-40_UTC.jpg,a picture of a woman in a red dress sits on a ...,picture red dress sits leather couch holding c...,a picture of a woman in a red dress sits on a ...,picture woman red dress sit leather couch hold...,"['picture NOUN', 'woman NOUN', 'red ADJ', 'dre...",[],red dress sit leather couch hold cell phone ...

In [3]:
df_codes = pd.read_excel('../0_data/long_short_code_equivalence.xlsx')
df_codes.head()

                          Long        Short
0  2015-11-18_18-26-59_UTC.jpg   -PHbiexlr_
1  2015-06-01_07-45-08_UTC.jpg   3YO1o0Rlkt
2  2015-07-06_10-38-30_UTC.jpg   4yqgDyxloK
3  2020-04-10_08-57-20_UTC.jpg  B-y2Fo8qcN_
4  2019-10-24_11-49-40_UTC.jpg  B3__d73i46x

In [4]:
print(len(df_codes))
print(len(df_autogen))

764
764

In [5]:
# merge dataframes to get shortcodes
df_merge1 = df_autogen.merge(df_codes, how ='left', on = 'Long')
df_merge1.head()

,Long,Auto_caption,clean_text,text_sup_clean,text_deep_clean,text_deep_clean_pos,hashtags,text_deep_clean_pos_str,Short
0,2015-11-18_18-26-59_UTC.jpg,a picture of a woman with long black hair sits...,picture long black hair sits couch front black...,a picture of a woman with long black hair sits...,picture woman long black hair sit couch front ...,"['picture NOUN', 'woman NOUN', 'long ADJ', 'bl...",[],long black hair sit couch front black firepl...,-PHbiexlr_
1,2015-06-01_07-45-08_UTC.jpg,a picture of a woman with black hair and a bla...,picture black hair black tattoo arm wears whit...,a picture of a woman with black hair and a bla...,picture woman black hair black tattoo arm wear...,"['picture NOUN', 'woman NOUN', 'black ADJ', 'h...",[],black hair black tattoo arm wear white dress...,3YO1o0Rlkt
2,2015-07-06_10-38-30_UTC.jpg,a picture of a woman with black hair and a bla...,picture black hair black tattoo arm poses whit...,a picture of a woman with black hair and a bla...,picture woman black hair black tattoo arm pose...,"['picture NOUN', 'woman NOUN', 'black ADJ', 'h...",[],black hair black tattoo arm pose white dress...,4yqgDyxloK
3,2020-04-10_08-57-20_UTC.jpg,a picture of a woman wearing a black jacket an...,picture wearing black jacket heels sits red co...,a picture of a woman wearing a black jacket an...,picture woman wear black jacket heel sit red c...,"['picture NOUN', 'woman NOUN', 'wear VERB', 'b...",[],wear black jacket heel sit red couch bare le...,B-y2Fo8qcN_
4,2019-10-24_11-49-40_UTC.jpg,a picture of a woman in a red dress sits on a ...,picture red dress sits leather couch holding c...,a picture of a woman in a red dress sits on a ...,picture woman red dress sit leather couch hold...,"['picture NOUN', 'woman NOUN', 'red ADJ', 'dre...",[],red dress sit leather couch hold cell phone ...,B3__d73i46x

In [11]:
df_merge1.columns

Index(['Long', 'Auto_caption', 'clean_text', 'text_sup_clean',
       'text_deep_clean', 'text_deep_clean_pos', 'hashtags',
       'text_deep_clean_pos_str', 'Short'],
      dtype='object')

In [12]:
df_merge1.columns = ['Long', 'Auto_caption', 'clean_text_auto', 'text_sup_clean_auto',
       'text_deep_clean_auto', 'text_deep_clean_pos_auto', 'hashtags_auto',
       'text_deep_clean_pos_str_auto', 'Short']

## Colapse photos into one post

In [27]:
joint_text = {}
for code in df_merge1['Short']:
    df_temp = df_merge1[df_merge1['Short'] == code]
    joined_string = df_temp['text_deep_clean_pos_str_auto'].str.cat(sep=' ')
    joint_text[code] = joined_string
len(joint_text)

260

In [29]:
# Convert to DataFrame
df_joint_text_auto = pd.DataFrame.from_dict(joint_text, orient='index').reset_index()

# Rename columns
df_joint_text_auto.columns = ['Short', 'text_deep_clean_pos_str_auto']
df_joint_text_auto

           Short                       text_deep_clean_pos_str_auto
0     -PHbiexlr_    long black hair sit couch front black firepl...
1     3YO1o0Rlkt    black hair black tattoo arm wear white dress...
2     4yqgDyxloK    black hair black tattoo arm pose white dress...
3    B-y2Fo8qcN_    wear black jacket heel sit red couch bare le...
4    B3__d73i46x    red dress sit leather couch hold cell phone ...
..           ...                                                ...
255  CzZIXBVMWdZ   smile white  brown eye small nose dark eyebro...
256  CzZMjcYMP21    long brown hair wear black coat blue jeans s...
257   fNO52Nxluy    black hair bare leg feature cover magazine r...
258   lzQl_gRlnD   young  long brown hair wear white lace dress ...
259   mrzAb-Rlkt   group beautiful  dress white purple dress pos...

[260 rows x 2 columns]

Import regular captions and join with long captions

In [30]:
df_captions = pd.read_excel('../0_data/captions_clean.xlsx')
df_captions.drop(columns =['Unnamed: 0', 'Long'], inplace = True)
df_captions.head()

,posts,caption,id,Short,link,Objectify (yes or no),clean_text,text_sup_clean,text_deep_clean,text_deep_clean_pos,hashtags,text_deep_clean_pos_str
0,2013-10-08_12-40-36_UTC.txt,Valentina Vignali looks explosive in a preciou...,216,fNO52Nxluy,https://www.instagram.com/p/fNO52Nxluy/?igshid...,1,valentina vignali looks explosive precious cou...,valentina vignali looks explosive in a preciou...,valentina vignali look explosive precious cout...,"['valentina PROPN', 'vignali PROPN', 'look VER...",[],valentina vignali look explosive precious cout...
1,2014-03-21_10-14-52_UTC.txt,Regram @nimabenati #amenstyle #amen #fashion #...,217,lzQl_gRlnD,https://www.instagram.com/p/lzQl_gRlnD/?igshid...,1,regram nimabenati amenstyle amen fashion nimab...,regram,regram,['regram PROPN'],"['amenstyle', 'amen', 'fashion', 'nimabenati',...",regram
2,2014-04-12_09-13-03_UTC.txt,RG @nimabenati #amencouture amenstyle.com\n,215,mrzAb-Rlkt,https://www.instagram.com/p/mrzAb-Rlkt/?igshid...,1,rg nimabenati amencouture,rg,NaN,[],['amencouture'],NaN
3,2015-06-01_07-45-08_UTC.txt,@emastokholma in Amen embroidered #dress from ...,214,3YO1o0Rlkt,https://www.instagram.com/p/3YO1o0Rlkt/?igshid...,1,emastokholma amen embroidered dress collection...,in amen embroidered from the spring summer co...,embroider spring summer collection discover more,"['embroider VERB', 'spring NOUN', 'summer NOUN...","['dress', 'amenstyle', 'ss15', 'emastokholma',...",embroider spring summer collection discover more
4,2015-07-06_10-38-30_UTC.txt,Stunning DJ @emastokholma wears all over paill...,213,4yqgDyxloK,https://www.instagram.com/p/4yqgDyxloK/?igshid...,1,stunning dj emastokholma wears paillettes dres...,stunning dj wears all over paillettes dress fr...,stunning dj wear all paillette dress last ss c...,"['stunning ADJ', 'dj ADV', 'wear NOUN', 'all A...","['dj', 'amenstyle', 'ss15', 'womenswear', 'oot...",stunning dj wear all paillette dress last ss c...

In [31]:
df_merge2 = df_joint_text_auto.merge(df_captions, how = 'left', on = 'Short')
df_merge2

,Short,text_deep_clean_pos_str_auto,posts,caption,id,link,Objectify (yes or no),clean_text,text_sup_clean,text_deep_clean,text_deep_clean_pos,hashtags,text_deep_clean_pos_str
0,-PHbiexlr_,long black hair sit couch front black firepl...,2015-11-18_18-26-59_UTC.txt,Stunning Mariana Rodriguez in #amencouture. Se...,207.0,https://www.instagram.com/p/-PHbiexlr_/?igshid...,1.0,stunning mariana rodriguez amencouture see ent...,stunning mariana rodriguez in see the entire c...,stunning mariana rodriguez see entire collection,"['stunning ADJ', 'mariana PROPN', 'rodriguez P...","['amencouture', 'amenstyle', 'ss16', 'womenswe...",stunning mariana rodriguez see entire collection
1,3YO1o0Rlkt,black hair black tattoo arm wear white dress...,2015-06-01_07-45-08_UTC.txt,@emastokholma in Amen embroidered #dress from ...,214.0,https://www.instagram.com/p/3YO1o0Rlkt/?igshid...,1.0,emastokholma amen embroidered dress collection...,in amen embroidered from the spring summer co...,embroider spring summer collection discover more,"['embroider VERB', 'spring NOUN', 'summer NOUN...","['dress', 'amenstyle', 'ss15', 'emastokholma',...",embroider spring summer collection discover more
2,4yqgDyxloK,black hair black tattoo arm pose white dress...,2015-07-06_10-38-30_UTC.txt,Stunning DJ @emastokholma wears all over paill...,213.0,https://www.instagram.com/p/4yqgDyxloK/?igshid...,1.0,stunning dj emastokholma wears paillettes dres...,stunning dj wears all over paillettes dress fr...,stunning dj wear all paillette dress last ss c...,"['stunning ADJ', 'dj ADV', 'wear NOUN', 'all A...","['dj', 'amenstyle', 'ss15', 'womenswear', 'oot...",stunning dj wear all paillette dress last ss c...
3,B-y2Fo8qcN_,wear black jacket heel sit red couch bare le...,2020-04-10_08-57-20_UTC.txt,Crystal Pumps ✨ #AmenStyle #AmenPreSpring20 #A...,209.0,https://www.instagram.com/p/B-y2Fo8qcN_/?igshi...,1.0,crystal pumps amenstyle amenaccessories,crystal pumps,crystal pump,"['crystal NOUN', 'pump VERB']","['amenstyle', 'amenprespring20', 'amenaccessor...",crystal pump
4,B3__d73i46x,red dress sit leather couch hold cell phone ...,2019-10-24_11-49-40_UTC.txt,Discover our FW19 Collection on amenstyle.com ...,200.0,https://www.instagram.com/p/B3__d73i46x/?igshi...,1.0,discover collection link bio shop line amensty...,discover our fw collection on link in bio shop...,discover fw collection link bio shop line now,"['discover VERB', 'fw PROPN', 'collection NOUN...","['amenstyle', 'amenfw19', 'declareyoursparkle']",discover fw collection link bio shop line now
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,CzZIXBVMWdZ,smile white brown eye small nose dark eyebro...,2023-11-08_17-00-38_UTC.txt,”GUIRLANDE” with @kendalljenner\nThe holiday c...,7.0,https://www.instagram.com/p/CzZIXBVMWdZ/?img_i...,1.0,guirlande kendalljenner holiday collection,guirlande with the holiday collection out now...,guirlande holiday collection out now jacquemus...,"['guirlande NOUN', 'holiday NOUN', 'collection...",[],guirlande holiday collection out now jacquemus...
276,CzZMjcYMP21,long brown hair wear black coat blue jeans s...,2023-11-08_17-37-17_UTC.txt,This season must-have. @fashionhurricanebyv in...,235.0,https://www.instagram.com/p/CzZMjcYMP21/?utm_s...,0.0,season fashionhurricanebyv nikola padded trenc...,this season must have in our wool cashmere nik...,season have wool cashmere nikola padded trench...,"['season NOUN', 'have VERB', 'wool NOUN', 'cas...","['thefrankieshop', 'frankieforall', 'frankiegi...",season have wool cashmere nikola padded trench...
277,fNO52Nxluy,black hair bare leg feature cover magazine r...,2013-10-08_12-40-36_UTC.txt,Valentina Vignali looks explosive in a preciou...,216.0,https://www.instagram.com/p/fNO52Nxluy/?igshid...,1.0,valentina vignali looks explosive precious cou...,valentina vignali looks explosive in a preciou...,valentina vignali look explosive precious cout...,"['valentina PROPN', 'vignali PROPN', 'look VER...",[],valentina vignali look explosive precious cout...
278,lzQl_gRlnD,young long brown hair wear white lace dress ...,2014-03-21_10-14-52_UTC.txt,Regram @nimabenati #amenstyle #amen #fashion #...,217.0,https://www.instagram.com/p/lzQl_gRlnD/?igshid...,1.0,regram nimabenati amenstyle amen fashion nimab...,regram,regram,['regram PROPN'],"['amenstyle', 'amen', 'fashion', 'nimabenati',...",regram
279,mrzAb-Rlkt,group beautiful dress white purple dress pos...,2014-04-12_09-13-03_UTC.txt,RG @nimabenati #amencouture amenstyle.com\n,215.0,https://www.instagram.com/p/mrzAb-Rlkt/?igshid...,1.0,rg nimabenati amencouture,rg,NaN,[],['amencouture'],NaN

In [35]:
df_merge2.columns

Index(['Short', 'text_deep_clean_pos_str_auto', 'posts', 'caption', 'id',
       'link', 'Objectify (yes or no)', 'clean_text', 'text_sup_clean',
       'text_deep_clean', 'text_deep_clean_pos', 'hashtags',
       'text_deep_clean_pos_str'],
      dtype='object')

In [36]:
# drop useless cols
df_final = df_merge2[['id','Short',
                      'Objectify (yes or no)', 
                      'text_deep_clean_pos_str', 'text_deep_clean_pos_str_auto']]
df_final.head()

,id,Short,Objectify (yes or no),text_deep_clean_pos_str,text_deep_clean_pos_str_auto
0,207.0,-PHbiexlr_,1.0,stunning mariana rodriguez see entire collection,long black hair sit couch front black firepl...
1,214.0,3YO1o0Rlkt,1.0,embroider spring summer collection discover more,black hair black tattoo arm wear white dress...
2,213.0,4yqgDyxloK,1.0,stunning dj wear all paillette dress last ss c...,black hair black tattoo arm pose white dress...
3,209.0,B-y2Fo8qcN_,1.0,crystal pump,wear black jacket heel sit red couch bare le...
4,200.0,B3__d73i46x,1.0,discover fw collection link bio shop line now,red dress sit leather couch hold cell phone ...

In [39]:
df_final['All_text'] = df_final['text_deep_clean_pos_str'] + ' ' + df_final['text_deep_clean_pos_str_auto']
df_final.head()

C:\Users\danie\AppData\Local\Temp\ipykernel_1492\2056160689.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['All_text'] = df_final['text_deep_clean_pos_str'] + ' ' + df_final['text_deep_clean_pos_str_auto']

,id,Short,Objectify (yes or no),text_deep_clean_pos_str,text_deep_clean_pos_str_auto,All_text
0,207.0,-PHbiexlr_,1.0,stunning mariana rodriguez see entire collection,long black hair sit couch front black firepl...,stunning mariana rodriguez see entire collecti...
1,214.0,3YO1o0Rlkt,1.0,embroider spring summer collection discover more,black hair black tattoo arm wear white dress...,embroider spring summer collection discover mo...
2,213.0,4yqgDyxloK,1.0,stunning dj wear all paillette dress last ss c...,black hair black tattoo arm pose white dress...,stunning dj wear all paillette dress last ss c...
3,209.0,B-y2Fo8qcN_,1.0,crystal pump,wear black jacket heel sit red couch bare le...,crystal pump wear black jacket heel sit red ...
4,200.0,B3__d73i46x,1.0,discover fw collection link bio shop line now,red dress sit leather couch hold cell phone ...,discover fw collection link bio shop line now ...

In [40]:
df_final.columns = ['id','Short',
                      'Objectify', 
                      'clean_caption', 'clean_autocaption', 'All_text']
df_final

,id,Short,Objectify,clean_caption,clean_autocaption,All_text
0,207.0,-PHbiexlr_,1.0,stunning mariana rodriguez see entire collection,long black hair sit couch front black firepl...,stunning mariana rodriguez see entire collecti...
1,214.0,3YO1o0Rlkt,1.0,embroider spring summer collection discover more,black hair black tattoo arm wear white dress...,embroider spring summer collection discover mo...
2,213.0,4yqgDyxloK,1.0,stunning dj wear all paillette dress last ss c...,black hair black tattoo arm pose white dress...,stunning dj wear all paillette dress last ss c...
3,209.0,B-y2Fo8qcN_,1.0,crystal pump,wear black jacket heel sit red couch bare le...,crystal pump wear black jacket heel sit red ...
4,200.0,B3__d73i46x,1.0,discover fw collection link bio shop line now,red dress sit leather couch hold cell phone ...,discover fw collection link bio shop line now ...
...,...,...,...,...,...,...
275,7.0,CzZIXBVMWdZ,1.0,guirlande holiday collection out now jacquemus...,smile white brown eye small nose dark eyebro...,guirlande holiday collection out now jacquemus...
276,235.0,CzZMjcYMP21,0.0,season have wool cashmere nikola padded trench...,long brown hair wear black coat blue jeans s...,season have wool cashmere nikola padded trench...
277,216.0,fNO52Nxluy,1.0,valentina vignali look explosive precious cout...,black hair bare leg feature cover magazine r...,valentina vignali look explosive precious cout...
278,217.0,lzQl_gRlnD,1.0,regram,young long brown hair wear white lace dress ...,regram young long brown hair wear white lace...
279,215.0,mrzAb-Rlkt,1.0,NaN,group beautiful dress white purple dress pos...,NaN

In [42]:
df_final.groupby(['Objectify'])[['Objectify']].count()

           Objectify
Objectify
0.0               86
1.0              193

In [43]:
df_final.to_excel('../0_data/captions_autocaptons_clean.xlsx', index = False)