In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_links = pd.read_excel('../0_data/db_prod.xlsx') #this is the original table build by hand
df_links.head()

,id,link,Objectify (yes or no)
0,1,https://www.instagram.com/p/CzTyW00KYzC/,1.0
1,2,https://www.instagram.com/p/C0PzOJxhEv7/,0.0
2,3,https://www.instagram.com/p/CzxRQd0tbV6/,0.0
3,4,https://www.instagram.com/p/CzZIXBVMWdZ/?img_i...,1.0
4,5,https://www.instagram.com/p/CzZIXBVMWdZ/?img_i...,1.0

In [3]:
df_links.dropna(inplace = True)

In [4]:
links = df_links['link']
#links = links[0:10]

In [7]:
current_directory

'C:\\Users\\danie\\Documents\\GitHub\\network_science\\3_wrangling'

In [8]:
import os

# Get the current working directory

# Specify the folder path you want to search for text files in
folder_path =  '../0_data/downloaded_posts'

# List all files in the folder
files = os.listdir(folder_path)

# Filter out only the text files (files with a .txt extension)
txt_files = [file for file in files if file.endswith('.txt')]
len(txt_files)

259

In [9]:
import os
# Folder to save the posts
download_folder = 'downloaded_posts'
os.makedirs(download_folder, exist_ok=True)
shortcodes = []
ids = df_links['id']
dict_ids_codes = {}
for link, id in zip(links, ids):
    shortcode = link.split('/')[-2]
    dict_ids_codes[id] = shortcode

In [10]:
dict_ids_codes

{1: 'CzTyW00KYzC',
 2: 'C0PzOJxhEv7',
 3: 'CzxRQd0tbV6',
 4: 'CzZIXBVMWdZ',
 5: 'CzZIXBVMWdZ',
 6: 'CzZIXBVMWdZ',
 7: 'CzZIXBVMWdZ',
 8: 'CzT-taQMeDF',
 9: 'CzRZny6MHUv',
 10: 'CxqTYrTMHID',
 11: 'CxqTYrTMHID',
 12: 'Cxfl2VssMoN',
 13: 'Cxfl2VssMoN',
 14: 'CuzvxUFsba2',
 15: 'CuzvxUFsba2',
 16: 'CuwfGI6s9q9',
 17: 'CtrYa6LM7ZD',
 18: 'CtrYa6LM7ZD',
 19: 'CtrYa6LM7ZD',
 20: 'CsjS4NbMy1c',
 21: 'CsRNN-us2lf',
 22: 'CsRNN-us2lf',
 23: 'CsRNN-us2lf',
 24: 'CqLU0uiDeSZ',
 25: 'CqLU0uiDeSZ',
 26: 'Copm4TxsIVi',
 27: 'CmFGPYkM5AQ',
 28: 'Cll7fIRsuo2',
 29: 'CiaXyUYsqcJ',
 30: 'CfWb4Uvs0hp',
 31: 'CfWb4Uvs0hp',
 32: 'CUXm0ziMX_s',
 33: 'CUXm0ziMX_s',
 34: 'CS7G8jLCAr_',
 35: 'CS12K0iMnl_',
 36: 'CKMPYM2sVxd',
 37: 'CKMNRR8spKS',
 38: 'CHGcWB8DfNa',
 39: 'CBTO1lXjrAA',
 40: 'CBTO1lXjrAA',
 41: 'CAJCsMvjDS_',
 42: 'B_InZsOD0Aj',
 43: 'B_InFhIjr9j',
 44: 'B9XY-IjjDWt',
 45: 'B9UltWvIDjA',
 46: 'B8zBgZeD8bQ',
 47: 'C0XtzX8PW6V',
 48: 'C0UTXb0RHUw',
 49: 'Cz745KtrB_n',
 50: 'CztvKcKAvhR',
 51: 'Czhgc_dvPnV',
 52: 'CyzK_ClMLqG',
 53: 'CyPbxl1MahD',
 54: 'CxQfRCmgc2g',
 55: 'CqxwuUMAh1P',
 56: 'C0T94WpM4eT',
 57: 'Cx-6Ob-MG1n',
 58: 'CumW5lsMSPl',
 59: 'CpQWgLfMAkS',
 60: 'CopA32MMPj_',
 61: 'CzvcjCvMlDb',
 62: 'CzqudKKtpxl',
 63: 'Czehr9KrCwj',
 64: 'Cy3O-Yysc1v',
 65: 'CywCd8iM03I',
 66: 'CyAnd_uNwJ_',
 67: 'Cxik4SuInww',
 68: 'C0JuzUvMK2B',
 69: 'CzlrsMDsFfc',
 70: 'Cx8wSMqL1FR',
 71: 'CxdGrHSxzSh',
 72: 'Cxah4Q0upWQ',
 73: 'CxNp5yItmJ9',
 74: 'Cwpmx0rxH3z',
 75: 'C0eCH7dKb3V',
 76: 'C0SJdFFKC_G',
 77: 'C0Q1XdhKULM',
 78: 'C0LrQoEs2f_',
 79: 'CyiGPWiqlba',
 80: 'C0b7pbjscVJ',
 81: 'C0CL6aJMqCi',
 82: 'Cr0ativsXMr',
 83: 'CpDATm-sGno',
 84: 'C0LqfLopkod',
 85: 'C0Gg3CiKkNY',
 86: 'C0D8Eh9rayl',
 87: 'Czyjr5XojbS',
 88: 'CzeSHA3r_Pf',
 89: 'C0UvM2UNU3w',
 90: 'C0H-DQlNFD8',
 91: 'C0H9dc8N_kZ',
 92: 'C0EJQ7ztfXA',
 93: 'C0WomKAI-BB',
 94: 'C0J0FEwIZXN',
 95: 'C0EbUh-ISrk',
 96: 'Cz6WvlHIthf',
 97: 'CyNkw4DI0Xi',
 98: 'CyNkw4DI0Xi',
 99: 'Czgv4QgPash',
 100: 'CyfhUluMPiC',
 101: 'CyqJBKxIC4c',
 102: 'Cx-2O1IoFIx',
 103: 'Cw5eSPJoA-p',
 104: 'CyGl_1Wsjye',
 105: 'Ct9GBxJs0kP',
 106: 'CsJfj3cown4',
 107: 'CZPwOJMI1OU',
 108: 'Cjkwkh_tS7K',
 109: 'Ci7zjVyK6a3',
 110: 'CgUeah1qtWy',
 111: 'CZXc563Lm0o',
 112: 'CZR9-VSLu3e',
 113: 'Cl6HMz8seZj',
 114: 'CxdGrHSxzSh',
 115: 'CxNp5yItmJ9',
 116: 'CqbIxPiMwz_',
 117: 'CqLy8FYtyz3',
 118: 'CovGK0avP-P',
 119: 'Cl_rmxVtLoJ',
 120: 'CkJc1zCKo90',
 121: 'CiFzsCMtJRq',
 122: 'ChZfzysNnrf',
 123: 'ChU4hHWN4tR',
 124: 'ChFb1wnNtA7',
 125: 'CgulNivq69s',
 126: 'CedMvEzKkk4',
 127: 'CcsciaFrGBX',
 128: 'CZ48_ERok7n',
 129: 'CYHp_v-tLBJ',
 130: 'CYEb9bUIHuz',
 131: 'CXtDIq3oueE',
 132: 'CWn9ICCNqfm',
 133: 'CUsrjjZIqBH',
 134: 'CUDe3G9IBq5',
 135: 'CTsTxMXI-1F',
 136: 'C0ep0HMB_3p',
 137: 'C0WZFxdv6yY',
 138: 'C0UWpWvBYtw',
 139: 'C0UCDN7MgPP',
 140: 'C0MTo8aL1Qs',
 141: 'C0JhHKVLk0J',
 142: 'C0ElQ7HLOET',
 143: 'Cz824fxLiuv',
 144: 'Cz8ey7_L-Q5',
 145: 'CzqnmFaPkX-',
 146: 'Czld_aqhEau',
 147: 'Czg2twNLU8O',
 148: 'CzgUYx_CjJD',
 149: 'CzdvomxpzT_',
 150: 'CzbONHMIp0u',
 151: 'CzEXpMYL5Pd',
 152: 'Cy0i2bGO9xM',
 153: 'CyvZVLAqFS5',
 154: 'CyqTGcxv-zP',
 155: 'Cylocs3BiS0',
 156: 'CylGF32tNRY',
 157: 'CyD1eAsBiWq',
 158: 'CyBGX1VJKWB',
 159: 'Cx_Ae0BJwP_',
 160: 'CxcBxNxhLW9',
 161: 'CxF0qL0JmG_',
 162: 'CwK0Grss9GZ',
 163: 'CwA1h-4sAXT',
 164: 'Cv7XV00uJlc',
 165: 'Cv4hYOArunp',
 166: 'CvU5tkISsYh',
 167: 'CvSU6cyptIu',
 168: 'CvR84vTJqiH',
 169: 'CvK0Q_0hFdU',
 170: 'CvKcOsgtoIC',
 171: 'CuzDWJoPr2N',
 172: 'CuZhIfYJcy6',
 173: 'CuUsJSKoPYA',
 174: 'CuHVRHUSNqO',
 175: 'Ct9g-_oLR6e',
 176: 'CtzNzlBr-Gk',
 177: 'Ctle5tULoaD',
 178: 'CtgjEICpQPQ',
 179: 'CtbjwOAhvm2',
 180: 'CtOvNvCSh9h',
 181: 'CtImrrJvZLr',
 182: 'CtEVKuhSNtj',
 183: 'CsyTmbJtRpi',
 184: 'Csgf9ORJz8c',
 185: 'Cz6mwpOKV6z',
 186: 'Cz9m4zVRIDs',
 187: 'Cxp3yuOMidv',
 188: 'CthFX1otDyN',
 189: 'CrjV6DiMMfQ',
 190: 'CrT5Hdstyaj',
 191: 'Co2gxs6Ik10',
 192: 'Co2gxs6Ik10',
 193: 'CljXn3BDpcn',
 194: 'CkYQVReOym8',
 195: 'CjN54aVh1HD',
 196: 'CiaA_vNjl4d',
 197: 'CdnkDKyjvLO',
 198: 'CdYim_Ij0z1',
 199: 'CPizZpNjDzT',
 200: 'B3__d73i46x',
 201: 'BmiLQlElqgG',
 202: 'BkcQY6FlNcN',
 203: 'BhePlPUljFR',
 204: 'BZQS9fIFDjO',
 205: 'BLDhgP7hg-h',
 206: 'BC3N8eFRlpm',
 207: '-PHbiexlr_',
 208: 'CJEcAKrs-7C',
 209: 'B-y2Fo8qcN_',
 210: 'Bvi3R68ALJP',
 211: 'BJn5LRbBpo8',
 212: 'BBIHpekRlhD',
 213: '4yqgDyxloK',
 214: '3YO1o0Rlkt',
 215: 'mrzAb-Rlkt',
 216: 'fNO52Nxluy',
 217: 'lzQl_gRlnD',
 218: 'Cz1F2pkoGNW',
 219: 'CzWFHoMICo0',
 220: 'CyN2z-YoqT5',
 221: 'CxX_6OqtqjQ',
 222: 'CwuzOiwNJ2H',
 223: 'CvzkyUDoTS6',
 224: 'CvWz4j1IiyZ',
 225: 'CtdtyVuNNNv',
 226: 'CsIuLbisBLv',
 227: 'Cr5YYyzs6Ot',
 228: 'Cp9ttssIBGd',
 229: 'C0bwbVxskqV',
 230: 'C0eVJZTMOSm',
 231: 'C0PNLV2Md0I',
 232: 'C0Eq5_isMaO',
 233: 'Cz6SMg6sDFK',
 234: 'Czy_v6xRg4I',
 235: 'CzZMjcYMP21',
 236: 'CzTwO8_sfr3',
 237: 'CyteauWxiPo',
 238: 'CxxuB4TMKwh',
 239: 'CzTyW00KYzC',
 240: 'CvMQ-z-ONEU',
 241: 'Cs_ddHKqyf8',
 242: 'CsqzXdkKfbZ',
 243: 'Cq0L6dZqGPu',
 244: 'CoKT2D2Kg0G',
 245: 'Cf_YGRgKs7h',
 246: 'CdA4OLQqe46',
 247: 'CbaED2oK-pA',
 248: 'CYRbUHtquPw',
 249: 'CYRbUHtquPw',
 250: 'CWi3kD-q1xZ',
 251: 'CUnA473KENK',
 252: 'CSqqD7uqa4M',
 253: 'CRRSZs6BswS',
 254: 'CQQKyIuFRxT',
 255: 'CIiZKTHHVmj',
 256: 'Czq4TMwrlZo',
 257: 'CzBtFadutfg',
 258: 'CwdACiNvoNo',
 259: 'CwFvBgNrriU',
 260: 'CvfDNUBOZcs',
 261: 'Ctt7Qe1ushu',
 262: 'CryFoOGOBt5',
 263: 'CrV02jtuXBt',
 264: 'CswH7mVodab',
 265: 'CeqjCb7I-wP',
 266: 'CW6AeAVq3tJ',
 267: 'COVXYFIh7YA',
 269: 'C0Y8rSqMl8T',
 270: 'C0MA5KQsLKS',
 271: 'CztofkpMPOo',
 272: 'C0jR0I8tGEl',
 273: 'CzWZ6R6qdbl',
 274: 'CyDCWb7K0mQ',
 275: 'CxzwTV1gh88',
 276: 'CuoYI__o4IZ',
 277: 'Cra4qYsMi9C',
 278: 'CrfngGbgTBF',
 279: 'Cy3AwyyMlvd',
 280: 'CystloQtc3B',
 281: 'CxnMNwKsphQ',
 282: 'Cu6q25Us_XC',
 283: 'CtjBFvLtulX'}

In [14]:
import os
import json
import lzma

# Specify the directory you want to search
directory = '../0_data/downloaded_posts'
codes_dict = {}
# List all files ending with .xz in the specified directory
xz_files = [file for file in os.listdir(directory) if file.endswith('.xz')]

for file in xz_files:
    # Open and decompress the .xz file
    file_short = file.split('.')[0]
    file_path = directory + '/' + file
    with lzma.open(file_path, 'rt') as file:
        data = json.load(file)
        
    codes_dict[file_short] = data['node']['shortcode']

### Turn to table and merge

In [16]:
df_long_codes = pdf = pd.DataFrame(list(codes_dict.items()), columns=['Long', 'Short'])
df_long_codes.head()

                      Long       Short
0  2013-10-08_12-40-36_UTC  fNO52Nxluy
1  2014-03-21_10-14-52_UTC  lzQl_gRlnD
2  2014-04-12_09-13-03_UTC  mrzAb-Rlkt
3  2015-06-01_07-45-08_UTC  3YO1o0Rlkt
4  2015-07-06_10-38-30_UTC  4yqgDyxloK

In [17]:
df_short_codes = pdf = pd.DataFrame(list(dict_ids_codes.items()), columns=['id', 'Short'])
df_short_codes.head()

   id        Short
0   1  CzTyW00KYzC
1   2  C0PzOJxhEv7
2   3  CzxRQd0tbV6
3   4  CzZIXBVMWdZ
4   5  CzZIXBVMWdZ

In [18]:
df_merge = df_short_codes.merge(df_long_codes, how='left', on = 'Short')
print(len(df_merge))

282

In [19]:
df_merge

      id        Short                     Long
0      1  CzTyW00KYzC  2023-11-06_15-12-10_UTC
1      2  C0PzOJxhEv7  2023-11-29_22-34-09_UTC
2      3  CzxRQd0tbV6  2023-11-18_02-00-09_UTC
3      4  CzZIXBVMWdZ  2023-11-08_17-00-38_UTC
4      5  CzZIXBVMWdZ  2023-11-08_17-00-38_UTC
..   ...          ...                      ...
277  279  Cy3AwyyMlvd  2023-10-26_11-00-25_UTC
278  280  CystloQtc3B  2023-10-22_11-00-18_UTC
279  281  CxnMNwKsphQ  2023-09-25_11-00-55_UTC
280  282  Cu6q25Us_XC  2023-07-20_11-00-38_UTC
281  283  CtjBFvLtulX  2023-06-16_10-01-12_UTC

[282 rows x 3 columns]

In [20]:
nan_counts = df_merge.isna().sum()

# Display the count of NaNs per column
print(nan_counts)

id       0
Short    0
Long     3
dtype: int64

In [21]:
df_final = df_merge.merge(df_links, how='left', on = 'id')
df_final.to_excel('../0_data/dataframe_codigos.xlsx')